server:
 port: 80
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1
    driver-class-name: org.h2.Driver
  h2:
    console:
     enabled: true
     path: /h2-console
  jpa:
    show_sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
logging:
 level:
  org:
   hibernate:
    type:
     descriptor:
      sql: trace